version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_ROOT_PASSWORD: tiger  # Root password
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  spring-boot-app:
    build: .
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root  # Use root for the database user
      SPRING_DATASOURCE_PASSWORD: tiger  # Root password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

volumes:
  mysqldata:
 